comment:
  on-update: recreate

#  header: |
#    Thank you for contributing to this repository :tada:.
#
#  footer: |
#    ---
#    Automated comment created by [PR Commenter](https://github.com/exercism/pr-commenter-action) :robot:.

  snippets:
    - id: drizzle-schema-changed
      files:
        - '**/schema.ts'
      body: |
        <h3> :warning: Drizzle schema file has been modified :warning: </h3>
        Please make sure to review and deploy it using Turso CLI before merging the PR.