export const logMsg = {
  TRACK_ROOM_EVENT: "TRACK_ROOM_EVENT",
  TRACK_PAGE_VIEW: "TRACK_PAGE_VIEW",
} as const;

export const logEndpoint = {
  TRACK_PAGE_VIEW: "TRACK_PAGE_VIEW",
  TRACK_EVENT: "TRACK_EVENT",
  TRACK_ESTIMATION: "TRACK_ESTIMATION",
} as const;

export const roomEvent = {
  ENTER_DIRECTLY: "ENTER_DIRECTLY",
  ENTER_EXISTING_ROOM: "ENTER_EXISTING_ROOM",
  ENTER_NEW_ROOM: "ENTER_NEW_ROOM",
  ENTER_RANDOM_ROOM: "ENTER_RANDOM_ROOM",
  ENTER_RECENT_ROOM: "ENTER_RECENT_ROOM",
  LEAVE_ROOM: "LEAVE_ROOM",
} as const;
