name: Lighthouse

on:
  pull_request:

jobs:
  generate_lighthouse_audit:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Add comment to PR
        id: loading_comment_to_pr
        uses: marocchino/sticky-pull-request-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.issue.number }}
          header: lighthouse
          message: |
            Running Lighthouse audit...
      - run: sleep 80 # TODO: switch to wait-for-vercel-action
      - name: Capture Vercel preview URL # https://github.com/zentered/vercel-preview-url#usage
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          GITHUB_REF: 'master'
          GITHUB_REPOSITORY: 'jkrumm/free-planning-poker'
        with:
          vercel_project_id: 'prj_u5ZbV2zIBqxpTdxhi6cjRlkrmvvA'
      - uses: actions/checkout@v3
        if: ${{ steps.vercel_preview_url.outputs.vercel_preview_url != '' }}
      - name: Audit preview URL with Lighthouse
        if: ${{ steps.vercel_preview_url.outputs.vercel_preview_url != '' }}
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}
          #            ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}/analytics
          #            ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}/roadmap
          #            ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}/contact
          #            ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}/imprint
          uploadArtifacts: true
          temporaryPublicStorage: true
      #          runs: 5
      - name: Format lighthouse score
        if: ${{ steps.vercel_preview_url.outputs.vercel_preview_url != '' }}
        id: format_lighthouse_score
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const result = ${{ steps.lighthouse_audit.outputs.manifest }}[0].summary
            const links = ${{ steps.lighthouse_audit.outputs.links }}

            const formatResult = (res) => Math.round((res * 100))
            Object.keys(result).forEach(key => result[key] = formatResult(result[key]))

            const score = res => res >= 90 ? '🟢' : res >= 50 ? '🟠' : '🔴'

            const comment = [
                `⚡️ [Lighthouse report](${Object.values(links)[0]}) for the changes in this PR:`,
                '| Category | Score |',
                '| --- | --- |',
                `| ${score(result.performance)} Performance | ${result.performance} |`,
                `| ${score(result.accessibility)} Accessibility | ${result.accessibility} |`,
                `| ${score(result['best-practices'])} Best practices | ${result['best-practices']} |`,
                `| ${score(result.seo)} SEO | ${result.seo} |`,
                `| ${score(result.pwa)} PWA | ${result.pwa} |`,
                ' ',
                `*Lighthouse ran on [${Object.keys(links)[0]}](${Object.keys(links)[0]})*`
            ].join('\n')

             core.setOutput("comment", comment);
      - name: Add comment to PR
        if: ${{ steps.vercel_preview_url.outputs.vercel_preview_url != '' }}
        id: comment_to_pr
        uses: marocchino/sticky-pull-request-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.issue.number }}
          header: lighthouse
          message: |
            ${{ steps.format_lighthouse_score.outputs.comment }}